### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by krishpranav** [admkopec/OS#1]
can you tell how to build it?? using xcode

**Comment by krishpranav** [comment]
should i clone it in xcode and build it??
can you tell me the full explanasion on how to build this os or can you implement that in README.md

**Comment by admkopec** [comment]
Yes, that's the main idea, once you clone it and open the **BetaOS.xcworkspace** file you should select the **_Kernel_** target. It's the main target the **Kernel.xcodeproj** file. This should build the whole project, however the last version of Xcode that I used to build this and have tested was **Xcode 10**. I suspect that there might be a few issues, which would have to be fixed to make the project compile under newer versions of Xcode and newer macOS SDKs.

**Comment by krishpranav** [comment]
so after building the project how to boot it??

**Comment by admkopec** [comment]
You need to have a properly prepared disk, which you can restore from the images attached to the releases _0.30_, _0.31_ or _0.31.1_ or by copying the contents of one of the available zip files. There you can also find more detailed explanations about booting the project. Once you have restored the image or copied the contents of a zip file. You can replace the **_Kernel_** executable with the one you build yourself.

**Comment by krishpranav** [comment]
thank you for the clear explanation
